name: Run Stock News Bot

on:
  schedule:
    - cron: "0 * * * *"  # Запуск раз в час
  
  workflow_dispatch:  # Позволяет запуск вручную

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Установка зависимостей
        run: |
          pip install yfinance nltk pandas requests beautifulsoup4
          pip install googletrans==4.0.0-rc1  # ✅ Добавляем googletrans

      - name: Запуск скрипта
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python script.py
